language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE palettepicker_test;' -U postgres
- npm run migrate-test
- npm run seed-test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: vVdDKpdO0yRd9ogCVt4xHfSnTHcaIvIBgdnhIOpJ2PmY1hzmKwI+cj3j+jIp3FCBAOiEqXBnYWwluLYVxySHedq/XNB4hZKy0ZmOZKcxOyhirIgVUq0SDfoFfoCxGQ82W3y/xm1mGbv3tn7Ik18k15SE1+RItbruCQvgq8h+gRhXBFqUbtAj0YmpKSWAHVJh/9aAXYZyn0epuhFV1XrHuH0tYOnpFRdKOFrrgx2cJ+h2pZp9MOPqUn16amg9e3oGryg34aA38gTQkQh30mZMeP94GNYouOzZ4he3HXlqwRErENrCeL+x4GHGpAo4Iz1c2HzmdZc9BqWBTPvmO75uAZ88rg/uCbOKcjA9+l2thMr5vn0T/lJYzdmPWvsUyk6iyIaj7W/bHMumWghlg1f8BIKgiaGyFnMVRuw0AFaq/4Q0GVz1PbGFxg7ItJt+pAxZDEkY4M2yIYSlDgtzzgT+xA3CrkuJUqKch/VC51FLJtHdAEbPamue8jWWe97RDktR1T4QNVX8W3Oy5D46sCG80qUw0s605oGzg2MhS8A3R+ew7OVABUHZHRcnoGHQOhjMU7iPRiyaFi5ICESoy9ZoNqDk5FksWHnUkFMJubA/Doy6LIv6lCFKNzeKdyrrNeW7/xTFIZajvljHlD5YVw6htAN7H3W2YR1x8Jaid/Qe7hQ=
  app: palette-picker-jbbc